[package]
name = "sensor_hub"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rppal = { version = "0.13.1", features= ["hal"]}
thiserror = "1.0.30"


[[example]]
name = "ep0106"